### ISSUE TITLE
Remove android:fullBackupContent from AndroidManifest.xml

### ISSUE THREAD

**Issue by mikaelbartlett** [cloudinary/cloudinary_android#100]
I get a merge error with other libraries that also contains this.

Please remove this as the app should decide how to handle backup.

**Comment by roeeba** [comment]
Hi @mikaelbartlett, can you please let us know with which library it conflicts?

**Comment by mikaelbartlett** [comment]
Hi @roeeba 

https://github.com/pusher/push-notifications-android/issues/89 here's the link to the other library.

**Comment by roeeba** [comment]
Thanks, @mikaelbartlett. I'm assigning it to our mobile engineer to further investigate.

**Comment by michalkcloudinay** [comment]
Hi @waliahimanshu, 

I just want to update you that this was fixed in the Android SDK 2.3.1 version.
I will go ahead and close this for now. Do let us know if you have any issues.

Thanks

**Comment by TomerPacific** [comment]
@roeeba - I think this issue can be closed, no?
