### ISSUE TITLE
Deprecated reference to gradle compile in README

### ISSUE THREAD

**Issue by Ferdzz** [cloudinary/cloudinary_android#107]
The README.md file refers to the [installation steps when using Gradle](https://github.com/cloudinary/cloudinary_android/blob/master/README.md#gradle-integration). This is the same as documented in the [introduction to integration](https://cloudinary.com/documentation/android_integration#overview) on the Cloudinary website (which by the way suggests using 1.24, rather than the latest stable 1.26, but that's another issue). In the sample the command used is `compile`. This has been deprecated for a while now, and the current suggested way of adding dependencies is by using `implementation`

I would suggest you update the documentation so people with less knowledge may avoid using deprecated API, unless there is a specific reason for doing so

I am using `implementation 'com.cloudinary:cloudinary-android:1.26.0'` in my own project and it works fine

**Comment by nitzanj** [comment]
Thanks, fixed.
