### ISSUE TITLE
Web API calls behave differently on iOS and Android (and cURL)

### ISSUE THREAD

**Issue by josmas** [cloudinary/cloudinary_android#117]
## Bug report for Cloudinary React SDK
This is not an issue with the react SDK but when trying to run a fetch call directly to the API. Apologies if this is not the place to open this, couldn't find other repo.

## Describe the bug in a sentence or two.
An api DELETE call such as:
```
https://api_key:api_secret@api.cloudinary.com/v1_1/cloud_name/resources/image/upload?public_ids=image_public_uc6uzx

```

From cURL this would be:
```
curl -X DELETE https://api_key:api_secret@api.cloudinary.com/v1_1/cloud_name/resources/image/upload?public_ids=image_public_uc6uzx
```
cURL and iOS succeed in the call; Android returns a 401.

```
"status": "401 Unauthorized",
"www-authenticate": "Basic realm=\"Cloudinary\"",
"x-cld-error": "Invalid credentials",
[...]
"ok": false,
"status": 401,
```
while iOS responds with:
```
"status": "200 OK",
"vary": "Accept-Encoding",
[...]
"ok": true,
"status": 200,
```

Android and iOS calls are done with react native `fetch`. Same call, same code (except for cURL).

## Versions and Libraries (fill in the version numbers)
Expo 37.0.8
React Native 0.61

We have a current discussion about this issue [here](https://github.com/thunkable/thunkable-issues/issues/562). Any help would be greatly appreciated!

**Comment by asisayag2** [comment]
Moved to the correct repo.
@nitzanj

**Comment by michalkcloudinay** [comment]
Hi @josmas, In order to further investigate your issue, please open a ticket at https://support.cloudinary.com, with your cloud name. Thanks

**Comment by nitzanj** [comment]
This was handled through the support. For posterity, the issue is rooted in Java's `URLConnection` behaviour which doesn't accept `user:password` as part of the URL. Basic authentication is only supported through headers.

**Comment by josmas** [comment]
Thanks @nitzanj 
For completeness, this is the response I got:

```
const data = await postData('https://api.cloudinary.com/v1_1/<cloud name>/resources/image/upload?public_ids\[\]=<public_id of the resource>');
  console.log("data:"+JSON.stringify(data, null, 2));

async function postData(url = '') {
  console.log("url: "+url);
    const response = await fetch(url, {
        method: 'DELETE',
       headers: {
        'Authorization': 'Basic ${base64.encode(`${login}:${password}`)}'
      }
    });
    return await response.json();
}
```
