### ISSUE TITLE
Migrate away from any JCenter dependencies

### ISSUE THREAD

**Issue by Cronch** [cloudinary/cloudinary_android#122]
## Bug report for Cloudinary Android SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
When trying to remove jcenter from a project where we are using cloudinary sdk 1.30.0 we found an error because of an internal library (com.linkedin.android.litr:litr:1.1.0) that is not found on other repositories.
You could update that library (because newer versions are stored on other repositories like oss.sonatype.org) to avoid this problem.

More information about the JCenter migration https://developer.android.com/studio/build/jcenter-migration

## Issue Type (Can be multiple)
[ x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
Remove JCENTER from build.gradle repositories

## Error screenshots or Stack Trace (if applicable)
> Could not resolve all files for configuration 'xxxx'.
   > Could not resolve com.linkedin.android.litr:litr:1.1.0.
     Required by:
         project :xxx > com.cloudinary:cloudinary-android:1.30.0 > com.cloudinary:cloudinary-android-preprocess:1.30.0
      > Could not resolve com.linkedin.android.litr:litr:1.1.0.

## Build System
[ ] Maven
[ x] Gradle
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[ x] No
[ ] Yes (specify model + Android version + vendor build number, if applicable)

## Versions and Libraries (fill in the version numbers)
Cloudinary Android SDK version 1.30.0
Android version 29
Gradle - 6.7.1 /

**Comment by michalkcloudinay** [comment]
Hi @Cronch, 
Thanks for reporting this. We opened an internal request to look into this issue, and we will update here once we have any new insights.

**Comment by Cronch** [comment]
Thank you!

**Comment by OsmanDroid** [comment]
Any update on this?

**Comment by michalkcloudinay** [comment]
@OsmanDroid  @LinusMuema, currently I don't have an ETA to share with you. I will let you know once we have new updates.

**Comment by mrea1** [comment]
This is blocking us from removing JCenter also

**Comment by michalkcloudinay** [comment]
We are currently working on a fix which should be released soon. We will keep you posted on this thread.

**Comment by michalkcloudinay** [comment]
We released a new version of the Android SDK with a fix for this issue. 
Please update to the new version and let us know if you have any issues.
Thanks
