### ISSUE TITLE
Bobyhwupload

### ISSUE THREAD

**Issue by bobyhw** [cloudinary/cloudinary_android#123]
Feature request for Cloudinary Android SDK
…(If your feature is for other SDKs, please request them there)

## Explain your use case
… (A high-level explanation of why you need this feature)

## Describe the problem you’re trying to solve
… (A more technical view of what you’d like to accomplish, and how this feature will help you achieve it)

## Do you have a proposed solution?
… (yes, no? Please elaborate if needed)

**Comment by bobyhw** [comment]
Yhank

**Comment by dannyv-cloudinary** [comment]
Hi @bobyhw.

I'm going to close this off as there is no information provided. Please feel free to open another issue if required, filling in all the required details.

Thanks,
-Danny
Developer Support Engineer @ Cloudinary
