### ISSUE TITLE
ANR in Android App for evernote library

### ISSUE THREAD

**Issue by slice-sunil** [cloudinary/cloudinary_android#144]
## Bug report for Cloudinary Android SDK
ANR in com.evernote.android.job.JobRescheduleService

## Describe the bug in a sentence or two.
We are unable to reproduce in test build but In production, several customers are getting ANR. 
We are using cloudinary version 1.26.0

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots or Stack Trace (if applicable)
…

## Build System
[ ] Maven
[ ] Gradle
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[ ] No
[ ] Yes (specify model + Android version + vendor build number, if applicable)

## Versions and Libraries (fill in the version numbers)
Cloudinary Android SDK version 1.26.0
Android version (Please provide exact [sdk level](https://developer.android.com/reference/android/os/Build.VERSION#SDK_INT))
Kotlin version (if applicable) - 0.0.0
JVM (of the dev environment) - 0.0.0
Maven - 0.0.0 / N/A
Gradle - 0.0.0 / N/A

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by tamaracloudinary** [comment]
Hi there, 
ANR can be caused by many reasons. Could you please share some more details? 
Thanks,
Tamara

**Comment by slice-sunil** [comment]
@tamaracloudinary We use cloudinary to upload images and mp4 file. We are unable to reproduce the ANR. But in our play store console we can see ANR with the mentioned message. We are not using evernote sdk in our app.

**Comment by francistagbo** [comment]
@slice-sunil probably, you could try to update your SDK version to the latest one and let us know how it goes?

**Comment by adimiz1** [comment]
Evernote was replace with Android WorkManager.
