### ISSUE TITLE
java.lang.Exception not implemented..........

### ISSUE THREAD

**Issue by denison-mobimove** [cloudinary/cloudinary_android#15]
When executing:
 Map result = cloudinary.api().resource("sample", ObjectUtils.emptyMap());

![apistrat](https://cloud.githubusercontent.com/assets/11518093/8653348/f4013da0-2994-11e5-9de9-8af996dc4b0d.JPG)

**Comment by roeeba** [comment]
Hi @denison-mobimove, we apologize for the very delayed response. As it probably not relevant anymore, we're closing this issue. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.
