### ISSUE TITLE
Is `v2.5.1` a faulty release?

### ISSUE THREAD

**Issue by gmazzo** [cloudinary/cloudinary_android#162]
Gradle Sync is failing after bumping to `2.5.1`.

After inspecting Maven Central, I found out it seems to be in a weird state, where some `2.5.1` artifacts are missing, and others are there but not indexed.

For instance, https://repo1.maven.org/maven2/com/cloudinary/cloudinary-android/2.5.1/ is there, but if you go one level up, https://repo1.maven.org/maven2/com/cloudinary/cloudinary-android/ the latest version you'll see is 2.5.0 🤷‍♂️ , while its [maven-metadata](https://repo1.maven.org/maven2/com/cloudinary/cloudinary-android/maven-metadata.xml) points to 2.5.1. Other pieces of the library are directly missing, like `cloudinary-android-preprocess`

```
   > Could not find com.cloudinary:cloudinary-android-preprocess:2.5.1.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/cloudinary/cloudinary-android-preprocess/2.5.1/cloudinary-android-preprocess-2.5.1.pom
```

## Issue Type (Can be multiple)
[x] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
Bump to `2.5.1`

## Build System
[ ] Maven
[x] Gradle
[ ] Other (Specify)

**Comment by adimiz1** [comment]
It seems there was an issue with version 2.5.1
Please try again with version 2.6.1, that should solve the issue.
If the issue persists please reopen.
