### ISSUE TITLE
Large image upload

### ISSUE THREAD

**Issue by VihaanVerma89** [cloudinary/cloudinary_android#17]
Hey, Is there any image compression functionality provided while uploading large camera images ?

**Comment by TalLevAmi** [comment]
Currently no client side compression is performed. You can perform any supported transformation before the image is stored, but it will happen after the upload.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
