### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by vil02** [cloudinary/cloudinary_android#174]
## Bug report for Cloudinary Android SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
These classes:
- [`AdaptToScreenSizeFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/delivery/usecases/inner/adapt/AdaptToScreenSizeFragment.java),
- [`AndroidJobStrategyTest`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/androidTest/java/com/cloudinary/android/AndroidJobStrategyTest.java),
- [`BaseActivity`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/delivery/base/BaseActivity.java),
- [`Crop`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/preprocess/src/main/java/com/cloudinary/android/preprocess/Crop.java),
- [`DownloadRequestBuilderStrategy`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/download/src/main/java/com/cloudinary/android/download/DownloadRequestBuilderStrategy.java),
- [`DownloadRequestBuilder`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/download/DownloadRequestBuilder.java),
- [`ImagePreprocessChain`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/preprocess/src/main/java/com/cloudinary/android/preprocess/ImagePreprocessChain.java),
- [`ImageWidgetFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/widgets/image_widget/ImageWidgetFragment.java),
- [`Limit`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/preprocess/src/main/java/com/cloudinary/android/preprocess/Limit.java),
- [`LocalizationFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/delivery/transform/inner/localization/LocalizationFragment.java),
- [`MainActivity`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/MainActivity.java),
- [`MediaManager`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/MediaManager.java),
- [`NoCloudActivity`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/upload/NoCloudActivity.java),
- [`PreprocessChain`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/preprocess/PreprocessChain.java),
- [`Rotate`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/preprocess/src/main/java/com/cloudinary/android/preprocess/Rotate.java),
- [`SignatureProvider`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/signed/SignatureProvider.java),
- [`UploadChoiceFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/upload/UploadChoiceFragment.java),
- [`UploadFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/upload/UploadFragment.java),
- [`UploadRequest`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/UploadRequest.java),
- [`UploadWidgetFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/widgets/upload_widget/UploadWidgetFragment.java),
- [`UseCasesAdapter`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/delivery/usecases/inner/UseCasesAdapter.java),
- [`UseCasesFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/delivery/usecases/inner/UseCasesFragment.java),
- [`Utils`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/helpers/Utils.java),
- [`ValidationException`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/core/src/main/java/com/cloudinary/android/preprocess/ValidationException.java),
- [`WidgetsFragment`](https://github.com/cloudinary/cloudinary_android/tree/d720ddfe0e7e6b286338de2b06199d056e9755be/sample/src/main/java/com/cloudinary/sample/main/widgets/WidgetsFragment.java),

have some unused imports.

I would like to remove them.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[x] Other (Specify) - code quality

Related to #173.

**Comment by michal-sordyl-cloudinary** [comment]
@vil02 Feel free to work on that!
