### ISSUE TITLE
Support API level 34

### ISSUE THREAD

**Issue by TomerPacific** [cloudinary/cloudinary_android#178]
## Describe the bug in a sentence or two.
It was observed that for several libraries inside the SDK, the compileSdkVersion and targetSdkVersion is **33**, where the required compileSdkVersion is at least **34**.

- https://github.com/cloudinary/cloudinary_android/blob/master/core/build.gradle
- https://github.com/cloudinary/cloudinary_android/blob/master/all/build.gradle
- https://github.com/cloudinary/cloudinary_android/blob/master/download/build.gradle

This can prevent developers who want to upload their application to the Google Play Store.
[Reference](https://support.google.com/googleplay/android-developer/answer/11926878?hl=en)

Related to #173 

## Issue Type (Can be multiple)
[X] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
N/A

## Error screenshots or Stack Trace (if applicable)
N/A

## Build System
[ ] Maven
[X] Gradle
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[X] No
[ ] Yes (specify model + Android version + vendor build number, if applicable)

**Comment by TomerPacific** [comment]
I'd like to work on this if it is possible.

**Comment by TomerPacific** [comment]
Thanks, can you also add the Hacktoberfest label to the issue?

**Comment by esguerrat** [comment]
@TomerPacific the Hacktoberfest label is on the repo. That should be sufficient. I'm asking our mobile development team about the test credentials.

**Comment by TomerPacific** [comment]
@esguerrat - Any updates regarding test credentials?

**Comment by TomerPacific** [comment]
@esguerrat - I think this issue can be closed as the PR has been approved and merged.
