### ISSUE TITLE
How to remove image /client side/? merci

### ISSUE THREAD

**Issue by Fkut** [cloudinary/cloudinary_android#21]

**Comment by strausr** [comment]
@Fkut 

@Fkut  In the upload-preset edit page (on your account upload settings page), click on the "Advanced Options" button and set "Return delete token" to "YES".This will tell Cloudinary to include return the delete-token within the response JSON, which then can be utilized to remove the uploaded image in an unsigned manner (notice the token is only valid for 10 minutes).More information here: https://support.cloudinary.com/hc/en-us/articles/202521132-How-to-delete-an-image-from-the-client-side-
-- | --

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
