### ISSUE TITLE
Upload request is not cancelable.

### ISSUE THREAD

**Issue by viclasoft** [cloudinary/cloudinary_android#22]
Hi. I called MediaManager.get().cancelAllRequests(); but onProgress() in UploadCallback still calling

**Comment by yakirp** [comment]
Hi @viclasoft, current implantation of the JobManager does not allow to termination while uploading,
only threads that not started yet, will cancel.
It is on our roadmap to improve this implementation.

**Comment by nitzanj** [comment]
@viclasoft Thanks for your comments. The latest release supports requests cancellation, both pending and in-progress.
