### ISSUE TITLE
upload multiple images.

### ISSUE THREAD

**Issue by niteshgoel** [cloudinary/cloudinary_android#23]
When I tried something like :  

` for (int i = 0; i < imagePath.size(); i++) {
         MediaManager.get().upload(imagePath.get(i)).callback(new UploadCallback() {`

I am getting the same URL in all the call backs.

can I upload multiple images? How?

**Comment by yakirp** [comment]
@niteshgoel -
In order to understand the issue better, I need some more information. Can you please share with me `imagePath` and the entire code block?

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by Thejas88** [comment]
Still facing the issue

**Comment by yakirp** [comment]
Answered at #53
