### ISSUE TITLE
Signed Upload : provideSignature method gives zero size map

### ISSUE THREAD

**Issue by visuerp** [cloudinary/cloudinary_android#25]
I need to implement signed upload. Here is how I'm initializing cloudinary. 

            HashMap<String, String> config = new HashMap();
            config.put("cloud_name", "<myCloudName goes here>");
            MediaManager.init(getActivity(), new ServerSignatureProvider(getActivity()), config);

but provideSignature method in ServerSignatureProvider class gives zero size map. Am'I missing something? Please help me.

**Comment by marissa-masangcay** [comment]
Hi,

In order to help you better can you provide a little more context such as what is in getActivity() and what you have implemented on the server side? This will help us further investigate the matter at hand.

Thanks,
Marissa

**Comment by marissa-masangcay** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

Thanks!
