### ISSUE TITLE
upgrade to Evernote android-job 1.2.0

### ISSUE THREAD

**Issue by xinthink** [cloudinary/cloudinary_android#30]
Evernote published [version 1.2.0 of android-job library](http://blog.evernote.com/tech/2017/10/06/announcing-android-job-library-1-2-0/) recently, which brings a lot of improvements.
Please consider moving to the latest version of the lib.

**Comment by roeeba** [comment]
Hi, @xinthink. Thank you very much for pointing this out. I've forwarded your suggestion to our dev team to review. We'll definitely update if and when this will be applied.

**Comment by carloshwa** [comment]
This update is necessary to fix https://github.com/cloudinary/cloudinary_android/issues/29 too. The sooner the better :)

**Comment by carloshwa** [comment]
@roeeba I see a fix was merged 👍  When can we expect a release with the fix?

**Comment by nitzanj** [comment]
@carloshwa The version with the required fixes is now released. If there's anything else please let us know. Thanks.
