### ISSUE TITLE
Error:(121, 0) SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable. <a href="openFile:/Users/NsikakThompson/AndroidStudioProjects/cloudinary_android/lib/build.gradle">Open File</a>

### ISSUE THREAD

**Issue by Nsikaktopdown** [cloudinary/cloudinary_android#31]
Error:(121, 0) SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
<a href="openFile:/Users/NsikakThompson/AndroidStudioProjects/cloudinary_android/lib/build.gradle">Open File</a>

**Comment by yakirp** [comment]
Hi @Nsikaktopdown , It looks like a problem with your Android Studio configuration where the Android SDK path not found.

Are you using the SDK as a sub-project references?

**Comment by nachomunoz** [comment]
You have to import root folder instead of only "sample" one. Else build.gradle for module is not got and anything works

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by SG-shubhammaurya** [comment]
A problem occurred configuring root project 'connectivity'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable

**Comment by victorli-cloudinary** [comment]
Hi @SG-shubhammaurya, could you copy and paste the whole error? Have you imported the root folder as mentioned above?
