### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: endMs is out of range of [10000, 9223372036854775807] (too low)

### ISSUE THREAD

**Issue by kuhnp** [cloudinary/cloudinary_android#35]
> Fatal Exception: java.lang.IllegalArgumentException: endMs is out of range of [10000, 9223372036854775807] (too low)
       at com.evernote.android.job.util.JobPreconditions.checkArgumentInRange(JobPreconditions.java:269)
       at com.evernote.android.job.JobRequest$Builder.setExecutionWindow(JobRequest.java:615)
       at com.cloudinary.android.AndroidJobStrategy.executeRequestsNow(AndroidJobStrategy.java:103)
       at com.cloudinary.android.MediaManager.queueRoomFreed(MediaManager.java:210)
       at com.cloudinary.android.MediaManager.access$000(MediaManager.java:32)
       at com.cloudinary.android.MediaManager$1.onSuccess(MediaManager.java:82)
       at com.cloudinary.android.DefaultCallbackDispatcher$1.handleMessage(DefaultCallbackDispatcher.java:72)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6114)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

I got this error using 1.21.0, with the following code:

``` java
HashMap<String, Object> option = new HashMap<>();
                    option.put("signature", apiImageSignature.getSignature());
                    option.put("timestamp", apiImageSignature.getTimeStamp());
                    option.put("api_key", apiImageSignature.getApiKey());
                    option.put("upload_preset", apiImageSignature.getUploadPreset());

mediaManager.upload(fileUri).options(options)
                        .constrain(TimeWindow.immediate())
                        .policy(new UploadPolicy.Builder().maxRetries(1).build())
                        .callback(new UploadCallback() {
                            @Override
                            public void onStart(String requestId) {}
                            @Override
                            public void onProgress(String requestId, long bytes, long totalBytes) {}
                            @Override
                            public void onSuccess(String requestId, Map resultData) {
                                //success
                            }
                            @Override
                            public void onError(String requestId, ErrorInfo error) {
                                //error
                            }
                            @Override
                            public void onReschedule(String requestId, ErrorInfo error) {}
                        })
                        .dispatch())
```

**Comment by roeeba** [comment]
Hi, @kuhnp. In order to understand the issue better, we need some more information. Could you please share with us the following?

* Execution flow: how to reproduce the issue?
* Code causing the error.
* Your cloud name.
* Timeframe in which the error occurred. 

Thanks

**Comment by kuhnp** [comment]
Hi, I can not reproduce the issue locally, this was reported by our crash tracking tool, and it seems that it impacted quite a few of our users. Here is the code that handles image upload on our Cloudinary account:

``` java 
public Observable<String> uploadImage(Uri fileUri){
        return remoteRepository.createImageSignature()
                .map(apiImageSignature -> {
                    HashMap<String, Object> option = new HashMap<>();
                    option.put("signature", apiImageSignature.getSignature());
                    option.put("timestamp", apiImageSignature.getTimeStamp());
                    option.put("api_key", apiImageSignature.getApiKey());
                    option.put("upload_preset", apiImageSignature.getUploadPreset());
                    return option;
                })
                .flatMap(options -> Observable.create(e -> mediaManager.upload(fileUri)
                        .options(options)
                        .constrain(TimeWindow.immediate())
                        .policy(new UploadPolicy.Builder().maxRetries(1).build())
                        .callback(new UploadCallback() {
                            @Override
                            public void onStart(String requestId) {}
                            @Override
                            public void onProgress(String requestId, long bytes, long totalBytes) {}
                            @Override
                            public void onSuccess(String requestId, Map resultData) {
                                String id = (String) resultData.get("public_id");
                                String extension = (String) resultData.get("format");
                                e.onNext(id+"."+extension);
                            }

                            @Override
                            public void onError(String requestId, ErrorInfo error) {
                                e.onError(new Throwable(error.getDescription()));
                            }

                            @Override
                            public void onReschedule(String requestId, ErrorInfo error) {}
                        })
                        .dispatch())
                );
    }

```
Our cloud name is "sphere".

There is no particular time frame, the error seems to happen regularly.

Thanks a lot!

**Comment by roeeba** [comment]
Hi @kuhnp. Thank you very much for the detailed response. A fix has been deployed in our labs. We will push this to production by the beginning of next week. 
Update to follow.

**Comment by kuhnp** [comment]
Thank you very much for the fix!
Any ETA regarding the next release?

**Comment by roeeba** [comment]
Hi @kuhnp. A fix should be deployed early next week. Update to follow.

**Comment by roeeba** [comment]
Hi @kuhnp. Version 1.22.0 is now released with a fix to this issue. 
I'm closing this ticket now, but please feel free to re-open it if you still see issues.
