### ISSUE TITLE
Could not find com.android.support:support-core-utils:26.0.1

### ISSUE THREAD

**Issue by lby1992** [cloudinary/cloudinary_android#43]
I attempt to upgrade the Cloudinary android lib to `com.cloudinary:cloudinary-android:1.21.0`, and then get the following message while gradle project building:

> Error:Could not find com.android.support:support-core-utils:26.0.1.
Required by:
    project :appfriendscore > com.cloudinary:cloudinary-android:1.21.0

Why does it occur and how to resolve.

**Comment by yakirp** [comment]
Hi @lby1992 ,

You should have to update the support library to version 26 (from the SDK Manager).

Best, 
Yakir

**Comment by lby1992** [comment]
@yakirp Thank you, I had resolved it.
