### ISSUE TITLE
Slow upload

### ISSUE THREAD

**Issue by KingIdee** [cloudinary/cloudinary_android#49]
I use unsigned uploads at the moment. When I begin an upload, it takes sometime before it starts Say 6seconds. Its too long for me. I noticed the evernote android-job library is used. You sure you using `.startNow` method ?

**Comment by roeeba** [comment]
Hi @KingIdee. Evernote added the `.startNow` method quite recently, and we're not using it yet. It's on our roadmap to add it, though no ETA at the moment. We will update here on any progress done in this matter.

**Comment by KingIdee** [comment]
Alright. Good to hear!

**Comment by roeeba** [comment]
Hi @KingIdee, The method was added in the last version.
