### ISSUE TITLE
Tacking somuch time to upload

### ISSUE THREAD

**Issue by yateeshkota** [cloudinary/cloudinary_android#51]
Hi, I used cloundinary android sdk in my application. I face two problems  -
1.  when I used upload the image or video using unsinged method in like below code

String requestId = MediaManager.get().upload(uri).unsigned("test").option("public_id", uniqueId)
        .callback(new UploadCallback() {
    @Override
    public void onStart(String requestId) {

        if ((ProgressBar) findViewById(R.id.progressBarHorizontal) != null) {
            isPostUploading = true;
            ((ImageView) findViewById(R.id.img_video_icon)).setVisibility(View.GONE);
            ((RelativeLayout) findViewById(R.id.progressBarDialog)).setVisibility(View.VISIBLE);
            ((ImageView) findViewById(R.id.imgPreview)).setImageBitmap(bitmap);
            ((ImageView) findViewById(R.id.imgPreview)).setVisibility(View.VISIBLE);
            ((ProgressBar) findViewById(R.id.progressBarHorizontal)).setProgress(0);
        }
    }
    @Override
    public void onProgress(String requestId, long bytes, long totalBytes) {
    }
    @Override
    public void onSuccess(String requestId, Map resultData) {
        String img3 = uniqueId + ".jpg";
        String url = MediaManager.get().url().generate(img3);
        new PublishPostTask().execute(desc, role_id, "image", uniqueId, url);
        Log.d("msg", "role_id : " + role_id);
    }
    @Override
    public void onError(String requestId, ErrorInfo error) {
        String er = String.valueOf(error);
        Toast.makeText(HomeActivity.this, "error : " + er, Toast.LENGTH_LONG).show();
    }
    @Override
    public void onReschedule(String requestId, ErrorInfo error) {
    }
}).dispatch()

it will take too much time to upload I found a reason on debug time staring the request id to onStart method of call black it will take 2-3 mint then onStart to onSuccess it will upload in 15-20 second, why this problem is occur.
and I mention that I have some transformation set on unsinged methodso that can take time for uploading

2. after upload video I call web service and get the transformation url and play on toroplayer in recyclerview. I found null NullPointerException  in logcat . after 1-2 mint refresh the view and again I use the same url it will work. so that mean transformation take time and i asked u how much it will take time

**Comment by snarchio** [comment]
Hi, i have a similar issue
I downloaded your sample app from githhub and on some devices (a Samsung SM-G360F and on an Amazon tablet KFFOWI, both with android 5) the upload do not start immediately but after at least 120 seconds

Here the essential logcat
`10:38:04.295 12067-12514/com.cloudinary.android.sample D/JobProxy21: Schedule one-off jobInfo success, request{id=5, tag=CLD, transient=false}, start 00:00:00, end 03:00:00 (from now), reschedule count 0
10:40:21.445 12067-12584/com.cloudinary.android.sample D/PlatformJobService: Run job, request{id=5, tag=CLD, transient=false}, waited 00:02:17, start 00:00:00, end 03:00:00
10:40:21.465 12067-12584/com.cloudinary.android.sample I/JobExecutor: Executing request{id=5, tag=CLD, transient=false}, context PlatformJobService
10:40:24.885 12067-12585/com.cloudinary.android.sample I/JobExecutor: Finished job{id=5, finished=true, result=SUCCESS, canceled=false, periodic=false, class=UploadJob, tag=CLD}
10:40:24.885 12067-12584/com.cloudinary.android.sample D/PlatformJobService: Finished job, request{id=5, tag=CLD, transient=false} SUCCESS`

As you can see it waits for 2:17 minutes and it happens always.
In your demo app is already set `.constrain(TimeWindow.immediate())` as you suggested.
I tried also to play with `.backoffCriteria(1000, UploadPolicy.BackoffPolicy.LINEAR)` but without luck.

Any suggestion?

**Comment by yakirp** [comment]
Hi @yateeshkota , @snarchio ,
We already fixed this issue and we are going to publish it soon (already in master).

Yakir

**Comment by Deathhit** [comment]
Is this issue fixed now? I am still experiencing it in version 1.24.

**Comment by yakirp** [comment]
Hi @flexpeace ,

could you please share with me the SDK you are using? (Our SDK)

Thanks

**Comment by Deathhit** [comment]
Umm... I am sorry, but I am not @flexpeace. I did comment on this issue,
but I deleted my comment.

Yakir Perlin <notifications@github.com> 於 2018年7月30日 週一 下午1:37寫道：

**Comment by Deathhit** [comment]
I did experience the same issue. The version I used is likely

compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.24.0'


zerg 1111 <b9915034@gmail.com> 於 2018年7月30日 週一 下午2:10寫道：

**Comment by yakirp** [comment]
ok, great, so could you please try with our new version:
https://github.com/cloudinary/cloudinary_android/releases/tag/1.24.1

Please let me know if it works for you.

--Yakir

**Comment by yakirp** [comment]
Hi guys, we do find an issue with that implantation, and we are going to release a new version next week that will fix that.

Stay tuned!

**Comment by flexpeace** [comment]
@yakirp Thanks a lot for the update. We almost switched to AWS s3 directly. I will be on standby for update

**Comment by flexpeace** [comment]
@yakirp Any Update? Thanks

**Comment by yakirp** [comment]
@flexpeace Please let me check with the team

**Comment by yakirp** [comment]
@flexpeace 
Our Android  SDK has been updated to version 1.25.0:
https://github.com/cloudinary/cloudinary_android/releases/tag/1.25.0

We added `UploadRequest.startNow()` api to support immediate upload requests.

**Comment by flexpeace** [comment]
Thanks a lot. I will try it and provide feedback. I really appreciate it

**Comment by yakirp** [comment]
Hi @flexpeace 

I'm following up to see whether you had a chance to check this?

Please let me know if you have questions?

Thanks,
Yakir

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
