### ISSUE TITLE
Upload ByteArray fails

### ISSUE THREAD

**Issue by horsejockey** [cloudinary/cloudinary_android#52]
In `PayloadFactory` the parsed.getHost() can return null when you use byte[] upload.  Need a better way to handle the encoded data.  I'm not positive the reason for this. Looking at my encoded data it starts with a '/' character so it looks like bytes:///{rest of data}.  Maybe that makes the getHost() method fail?
I was uploading JPEG format image.

Similar issues with Webm.  current encoding produces new line characters.  getHost() only returns string up to first new line.

**Comment by yakirp** [comment]
Hi @horsejockey 

Could you please share with me the execution flow which reproduces the issue you referred to?

Looking forward to your response. 

Best,
Yakir

**Comment by horsejockey** [comment]
Sorry it took me a bit.  I was using Kotlin but I don't think that should matter.  I was trying to upload a `byteArray` or java `byte[]` instead of just passing the uri.  I debugged it a bit and ran into two different issues both having to do with the `parsed.getHost()` in `PayloadFactory` not working well with the base64 encoded `byte[]`.  You should be able to grab any image and try to upload it as a `byte[]` to reproduce. I definitely had the issue with jpeg encoded images and webm images. 

Here were my upload settings which are now working fine when I just pass the uri of the image.

```
MediaManager
            .get()
            .upload(bytes)
            .options(options)
            .unsigned("event-apps")
            .constrain(TimeWindow.immediate())
            .policy(
                UploadPolicy
                    .Builder()
                    .maxRetries(0)
                    .networkPolicy(UploadPolicy.NetworkType.ANY)
                    .build()
            ).callback(object : UploadCallback { Callback Methods }
```

**Comment by yakirp** [comment]
Hi @horsejockey ,

We fixed this issue in our latest SDK version, could you please make sure you are using it and let me know if it works for you?

Thanks,
Yakir
