### ISSUE TITLE
Multiple image upload in the loop issue

### ISSUE THREAD

**Issue by Thejas88** [cloudinary/cloudinary_android#53]
Trying to upload multiple images through android application and get the resultdata but override methods are called multiple times for same request id.

**Comment by yakirp** [comment]
Hi @Thejas88, 
This bug was fixed in version [1.23.0](https://github.com/cloudinary/cloudinary_android/releases/tag/1.23.0)

Make sure to use our latest version, and please let me know if it works for you.

**Comment by Thejas88** [comment]
@yakirp Its working after changing the version. Thanks for quick reply.
