### ISSUE TITLE
responsiveUrl function is not able to find in MediaManager.get() 

### ISSUE THREAD

**Issue by ababavali23** [cloudinary/cloudinary_android#58]
I am not able to add the lib folder can you please help me.

**Comment by shirlymanor** [comment]
Did you import the library?

import com.cloudinary.android.MediaManager;

Did you included this within the dependencies section of your build.gradle file:

compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.20.0'

**Comment by ababavali23** [comment]
Yes. I did this.
 compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.20.0'

// This is working fine 
MediaManager.get()
                        .url()
                        .transformation(new Transformation().radius(10).width(715).crop("scale"))
                        .generate(coupensList.get(position).getImageUrl()

//This is not working. responsiveUrl method is cannot resolve
MediaManager.get().responsiveUrl(AUTO_FILL)
                .generate("sample", imageView, new ResponsiveUrl.Callback() {
                    @Override
                    public void onUrlReady(Url url) {
                        // Use your favorite image download library to fetch the image, picasso example:
                        Picasso.with(context).load(url.generate()).into(holder.coupenImage);
                    }
                });

**Comment by yakirp** [comment]
Hi @ababavali23 ,
Responsive URL [added ](https://github.com/cloudinary/cloudinary_android/commit/93d1b29dac053deca5f98bdd53be2849aabf8c33#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR8)in version 1.24.0.

So this will fix the issue:
`compile group: 'com.cloudinary', name: 'cloudinary-android', version: '1.24.0'`

Best,
Yakir
