### ISSUE TITLE
When calling `MediaManager.get().upload()` then upload happens more than once

### ISSUE THREAD

**Issue by hayribakici** [cloudinary/cloudinary_android#59]
Hi,

sorry to ask this question here, but when I call
```
MediaManager.get().upload(file.absolutePath)
                    .callback(UploadListener())
                    .unsigned("mypreset")
                    .constrain(TimeWindow.immediate())
```
for some reason the android job scheduler fires multiple jobs to upload the image resulting them spamming the media library (70 images in 5 minues). 
Do I do something wrong or am I using the library in a wrong manner?

Thanks in advance

**Comment by yakirp** [comment]
@hayribakici Could you please share with me your the project?

**Comment by hayribakici** [comment]
hey!

Thank you for your quick response. The problem lied wrapping the upload in RxJava Observables. Apologies for the inconvenience. 

Sincerly

**Comment by yakirp** [comment]
Thanks for the update! So can I close this issue?

**Comment by hayribakici** [comment]
yes :)
