### ISSUE TITLE
There's no Upload Progress Information

### ISSUE THREAD

**Issue by diegosax** [cloudinary/cloudinary_android#6]
It'd be nice if there was a callback function with the updated byte transferred so we could show a progress bar to the user just like in the Jquery Direct Upload Plugin

**Comment by CsHimanshu** [comment]
I am really surprise when i got it there is no any callback for progress indication and cancel uploading for Android. There should be something for it.

**Comment by PimDeWitte** [comment]
We are going to have to switch platforms if this is not implemented ASAP. @cloudinary @codeinvain

**Comment by samyakjain** [comment]
+1

**Comment by nvhaiwork** [comment]
+1,

**Comment by mukundvis** [comment]
+1

**Comment by suyashgupta25** [comment]
+1

**Comment by sainathcholkarTal** [comment]
+1

**Comment by GopalSingh292** [comment]
+1

**Comment by vikash1711** [comment]
+1

**Comment by nishu-priya** [comment]
+1

**Comment by sunnytambi** [comment]
+1

**Comment by prathameshtal** [comment]
+1

**Comment by DefiantCatgirl** [comment]
+1

**Comment by roeeba** [comment]
Version 1.11.0 was released on https://github.com/cloudinary/cloudinary_java/tree/master/cloudinary-android (please see - https://github.com/cloudinary/cloudinary_java/issues/72). It includes the progress callback. We'll be closing this issue now, but please feel free to re-open it if you see any issues.
