### ISSUE TITLE
Getting IllegalStateException("Must call init() before accessing Cloudinary.");

### ISSUE THREAD

**Issue by noticeboard-priyansh** [cloudinary/cloudinary_android#71]
I am invoking MediaManager.init() at the app startup.
Randomly, if I try to access MediaManager().get(), it throws me IllegalStateException("Must call init() before accessing Cloudinary.");
Any idea, why? 
This has happened for few users and is random. Unable to reproduce it locally.

**Comment by yakirp** [comment]
Hi @noticeboard-priyansh 

I'm following up to see whether you had a chance to check this?

Please let me know if you have questions?

Thanks,
Yakir

**Comment by yakirp** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.Hi Raul,
