### ISSUE TITLE
Android - What is the proper way to get secure url.

### ISSUE THREAD

**Issue by NehaSukhlecha** [cloudinary/cloudinary_android#74]
cloudinary.url().generate(obj.getCloudinary_image_id()); 

gives http url, is there any method for https url or we need to do it manually.

**Comment by igy** [comment]
Hi Neha,
You can get a secure URL from the Android SDK in two ways.
For an individual image, you can specify the secure option when creating the url:

```
cloudinary.url().secure(true).generate(obj.getCloudinary_image_id());
```

You can also set the behaviour for all calls from the SDK by specifying the `secure` parameter when initialising the SDK. For example:
```
Map config = new HashMap();
config.put("cloud_name", "myCloudName");
config.put("secure", true);
MediaManager.init(this, config);
```

Let me know if you have any problems with that, or if you have any further questions.
You can also open a ticket for our support team at https://support.cloudinary.com
