### ISSUE TITLE
How can we pause or abort on going upload ?

### ISSUE THREAD

**Issue by Siddharthflo** [cloudinary/cloudinary_android#90]

**Comment by yakirp** [comment]
Hi,
You can cancel the request, please see this:
https://github.com/cloudinary/cloudinary_android/blob/4e8be2e6510add3f6d8db2f240950911cfb2d97a/lib/src/main/java/com/cloudinary/android/RequestDispatcher.java#L31

Please let me know if it works for you.
Thanks

**Comment by avinashSminq** [comment]
Same problem i facing with iOS app, I want to cancel an ongoing upload, how i can I handle it as i could not find any requestId for iOS.

**Comment by shirlymanor** [comment]
You can cancel the upload request. for example:
`let request = cloudinary.createUploader().signedUpload(url: URL(string: "http://res.cloudinary.com/demo/image/upload/sample")!, params:params);

request.cancel()
`

**Comment by avinashSminq** [comment]
Thanks for the update Shirly
