### ISSUE TITLE
Android O - java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by walkermanx** [cloudinary/cloudinary_android#96]
Android O - java.lang.RuntimeException: An error occurred while executing doInBackground() 

 coz com.evernote.android.job is a dependency of  lib .and com.evernote.android.job use a clz named JobIntentService which has a compatibility problem on Android O+ ,so can you guys fix it ,plz? 
this problem will cause crashes on our production app .  [here maybe is the solution](https://medium.com/@mohamed.zak/workaround-to-solve-securityexception-caused-by-jobintentservice-1f4b0e688a26)

[see also](https://github.com/evernote/android-job/issues/255)

**Comment by goeson7** [comment]
It seems to be resolved in [android-job v1.3.0](https://github.com/evernote/android-job/releases/tag/v1.3.0). Is there a version update schedule?

**Comment by aleksandar-cloudinary** [comment]
Hi @goeson7. I see you also raised this with us via Support where one of my colleagues has replied.  Just sharing the update in this thread too for anyone that runs across this. We've created a ticket internally for us to update the dependency, but for now, you can update the build file directly to include the v1.3.0 version for this library.

**Comment by roeeba** [comment]
Evernote dependency was updated to version 1.4.2.
